server:
  port: 28080
spring:
  redis:
    database: 0
    host: 192.168.32.13
    port: 6379
    password: 123456
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
